<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-03T09:49:54Z" name="Default suite" finished-at="2024-06-03T09:50:29Z" duration-ms="35258">
    <groups>
    </groups>
    <test started-at="2024-06-03T09:49:54Z" name="Default test" finished-at="2024-06-03T09:50:29Z" duration-ms="35258">
      <class name="com.comcast.crm.organizationtest.createAContactInMoreInfoTest">
        <test-method is-config="true" signature="configBS()[pri:0, instance:com.comcast.crm.organizationtest.createAContactInMoreInfoTest@5a7fe64f]" started-at="2024-06-03T09:49:53Z" name="configBS" finished-at="2024-06-03T09:49:54Z" duration-ms="68" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method is-config="true" signature="configBC()[pri:0, instance:com.comcast.crm.organizationtest.createAContactInMoreInfoTest@5a7fe64f]" started-at="2024-06-03T09:49:54Z" name="configBC" finished-at="2024-06-03T09:49:57Z" duration-ms="3294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method is-config="true" signature="configBM()[pri:0, instance:com.comcast.crm.organizationtest.createAContactInMoreInfoTest@5a7fe64f]" started-at="2024-06-03T09:49:57Z" name="configBM" finished-at="2024-06-03T09:50:04Z" duration-ms="6832" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method signature="creata_A_Contact()[pri:0, instance:com.comcast.crm.organizationtest.createAContactInMoreInfoTest@5a7fe64f]" started-at="2024-06-03T09:50:04Z" name="creata_A_Contact" finished-at="2024-06-03T09:50:26Z" duration-ms="21897" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.comcast.crm.organizationtest.createAContactInMoreInfoTest.creata_A_Contact(createAContactInMoreInfoTest.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creata_A_Contact -->
        <test-method is-config="true" signature="configAM()[pri:0, instance:com.comcast.crm.organizationtest.createAContactInMoreInfoTest@5a7fe64f]" started-at="2024-06-03T09:50:26Z" name="configAM" finished-at="2024-06-03T09:50:28Z" duration-ms="2806" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method is-config="true" signature="configAC()[pri:0, instance:com.comcast.crm.organizationtest.createAContactInMoreInfoTest@5a7fe64f]" started-at="2024-06-03T09:50:28Z" name="configAC" finished-at="2024-06-03T09:50:29Z" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method is-config="true" signature="configAS()[pri:0, instance:com.comcast.crm.organizationtest.createAContactInMoreInfoTest@5a7fe64f]" started-at="2024-06-03T09:50:29Z" name="configAS" finished-at="2024-06-03T09:50:29Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- com.comcast.crm.organizationtest.createAContactInMoreInfoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
